/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnimatedButton {
        /**
          * Action executed during the animation Use a async function or return a promise
          * @type {Function}
          * @memberof AnimatedButton
         */
        "action": Function;
        /**
          * Disable burst effect
          * @type {boolean}
          * @memberof AnimatedButton
         */
        "disableBurst": boolean;
        /**
          * The success text
          * @type {string}
          * @memberof AnimatedButton
         */
        "success": string;
        /**
          * The button text
          * @type {string}
          * @memberof AnimatedButton
         */
        "text": string;
    }
}
declare global {
    interface HTMLAnimatedButtonElement extends Components.AnimatedButton, HTMLStencilElement {
    }
    var HTMLAnimatedButtonElement: {
        prototype: HTMLAnimatedButtonElement;
        new (): HTMLAnimatedButtonElement;
    };
    interface HTMLElementTagNameMap {
        "animated-button": HTMLAnimatedButtonElement;
    }
}
declare namespace LocalJSX {
    interface AnimatedButton {
        /**
          * Action executed during the animation Use a async function or return a promise
          * @type {Function}
          * @memberof AnimatedButton
         */
        "action"?: Function;
        /**
          * Disable burst effect
          * @type {boolean}
          * @memberof AnimatedButton
         */
        "disableBurst"?: boolean;
        /**
          * The success text
          * @type {string}
          * @memberof AnimatedButton
         */
        "success"?: string;
        /**
          * The button text
          * @type {string}
          * @memberof AnimatedButton
         */
        "text"?: string;
    }
    interface IntrinsicElements {
        "animated-button": AnimatedButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "animated-button": LocalJSX.AnimatedButton & JSXBase.HTMLAttributes<HTMLAnimatedButtonElement>;
        }
    }
}
